### ISSUE TITLE
node-js-buy unhandled promise rejection

### ISSUE THREAD

**Issue by markwbrown** [Shopify/storefront-api-examples#47]
When attempting to add an item to the cart, I get: 
0|app      | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|app      | TypeError: Cannot read property 'id' of undefined
0|app      |     at productsPromise.then.products (/home/user/store.example.com/lib/app.js:77:85)
0|app      |     at process._tickDomainCallback (internal/process/next_tick.js:135:7)
0|app      | (node:15392) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'id' of undefined

Item does not get added to cart and eventually, I get a 504.

**Comment by minasmart** [comment]
the error message you're getting seem to be coming from whatever library you're using. The promise rejection error isn't the native promise rejection error. The one change that happened is that when the SDK can't resolve the data that's returned (there's server errors or you requested an invalid ID), instead of throwing an error and stopping execution, you're able to catch the error using the promise. This isn't a new error, you're just able to catch it now.

**Comment by markwbrown** [comment]
Thanks Mina. I'm using the shopify node-js-buy library. I don't believe I am requesting an invalid id, as the items I have added to shopify appear in the storefront view, but I have no way to verify the checkoutID value is valid. The error gets triggered when I click "add to cart". Seems like this is a server error.
